// Ascendancy configuration — generated from PoB 0.5 tree.json
// Main-tree nodes are scaled 2× so the centre opens up for ascendancy clusters.
// Transforms negate each cluster's mean position, centering it at (0,0).
// Node IDs are game PassiveSkills string table IDs (e.g. "AscendancyRanger1Start").

export const ascendancyData: Record<string, { nodes: string[]; transform: string }> = {
	Deadeye: { nodes: ["AscendancyRanger1Notable1", "AscendancyRanger1Notable2_1", "AscendancyRanger1Notable2_2", "AscendancyRanger1Notable2_Choice", "AscendancyRanger1Notable3", "AscendancyRanger1Notable4", "AscendancyRanger1Notable5_", "AscendancyRanger1Notable6", "AscendancyRanger1Notable7", "AscendancyRanger1Notable8", "AscendancyRanger1Small1__", "AscendancyRanger1Small2", "AscendancyRanger1Small3", "AscendancyRanger1Small4", "AscendancyRanger1Small5", "AscendancyRanger1Small6", "AscendancyRanger1Small7", "AscendancyRanger1Small8", "AscendancyRanger1Start"], transform: "translate(-16049.53, -1939.79)" },
	Pathfinder: { nodes: ["AscendancyRanger3Notable1_", "AscendancyRanger3Notable2", "AscendancyRanger3Notable4", "AscendancyRanger3Notable5", "AscendancyRanger3Notable6", "AscendancyRanger3Notable7_1", "AscendancyRanger3Notable7_2", "AscendancyRanger3Notable7_3", "AscendancyRanger3Notable7_4", "AscendancyRanger3Notable7_5", "AscendancyRanger3Notable7_Choice", "AscendancyRanger3Notable8_1", "AscendancyRanger3Notable8_3", "AscendancyRanger3Notable8_Choice_", "AscendancyRanger3Notable9", "AscendancyRanger3Small1", "AscendancyRanger3Small3", "AscendancyRanger3Small4", "AscendancyRanger3Small5", "AscendancyRanger3Small6", "AscendancyRanger3Small7", "AscendancyRanger3Small8", "AscendancyRanger3Small9", "AscendancyRanger3Start"], transform: "translate(-15465.50, -4968.75)" },
	Amazon: { nodes: ["AscendancyHuntress1Notable1", "AscendancyHuntress1Notable2", "AscendancyHuntress1Notable3", "AscendancyHuntress1Notable4", "AscendancyHuntress1Notable5", "AscendancyHuntress1Notable6", "AscendancyHuntress1Notable7", "AscendancyHuntress1Notable8", "AscendancyHuntress1Notable9", "AscendancyHuntress1Small1", "AscendancyHuntress1Small2", "AscendancyHuntress1Small3", "AscendancyHuntress1Small4_", "AscendancyHuntress1Small5", "AscendancyHuntress1Small6", "AscendancyHuntress1Small7", "AscendancyHuntress1Small8", "AscendancyHuntress1Small9", "AscendancyHuntress1Start"], transform: "translate(-13693.47, -8000.89)" },
	"Spirit Walker": { nodes: ["AscendancyHuntress2Notable1", "AscendancyHuntress2Notable2", "AscendancyHuntress2Notable3", "AscendancyHuntress2Notable4", "AscendancyHuntress2Notable5", "AscendancyHuntress2Notable6", "AscendancyHuntress2Notable7", "AscendancyHuntress2Notable8", "AscendancyHuntress2Notable9", "AscendancyHuntress2Small1", "AscendancyHuntress2Small2_", "AscendancyHuntress2Small3", "AscendancyHuntress2Small4", "AscendancyHuntress2Small5", "AscendancyHuntress2Small6", "AscendancyHuntress2Small7", "AscendancyHuntress2Small8", "AscendancyHuntress2Start"], transform: "translate(-11872.89, -10940.00)" },
	Ritualist: { nodes: ["AscendancyHuntress3Notable1_", "AscendancyHuntress3Notable2", "AscendancyHuntress3Notable3_", "AscendancyHuntress3Notable4", "AscendancyHuntress3Notable5", "AscendancyHuntress3Notable6", "AscendancyHuntress3Notable7", "AscendancyHuntress3Small1_1", "AscendancyHuntress3Small1_2_", "AscendancyHuntress3Small1_3", "AscendancyHuntress3Small2", "AscendancyHuntress3Small3", "AscendancyHuntress3Small4", "AscendancyHuntress3Small5", "AscendancyHuntress3Small6", "AscendancyHuntress3Small8", "AscendancyHuntress3Start"], transform: "translate(-9582.24, -12758.65)" },
	Titan: { nodes: ["AscendancyWarrior1Notable1", "AscendancyWarrior1Notable2", "AscendancyWarrior1Notable3", "AscendancyWarrior1Notable4", "AscendancyWarrior1Notable5", "AscendancyWarrior1Notable6", "AscendancyWarrior1Notable7", "AscendancyWarrior1Notable8", "AscendancyWarrior1Small1", "AscendancyWarrior1Small2", "AscendancyWarrior1Small3", "AscendancyWarrior1Small4", "AscendancyWarrior1Small5", "AscendancyWarrior1Small6", "AscendancyWarrior1Small7", "AscendancyWarrior1Small8", "AscendancyWarrior1Start"], transform: "translate(11977.82, -10636.82)" },
	Warbringer: { nodes: ["AscendancyWarrior2Notable1", "AscendancyWarrior2Notable2", "AscendancyWarrior2Notable3", "AscendancyWarrior2Notable4_", "AscendancyWarrior2Notable6", "AscendancyWarrior2Notable7", "AscendancyWarrior2Notable8", "AscendancyWarrior2Notable9", "AscendancyWarrior2Small1", "AscendancyWarrior2Small2", "AscendancyWarrior2Small3", "AscendancyWarrior2Small5", "AscendancyWarrior2Small6", "AscendancyWarrior2Small7_", "AscendancyWarrior2Small8", "AscendancyWarrior2Small9", "AscendancyWarrior2Start"], transform: "translate(14246.65, -7955.71)" },
	"Smith of Kitava": { nodes: ["AscendancyWarrior3Notable1", "AscendancyWarrior3Notable2", "AscendancyWarrior3Notable3", "AscendancyWarrior3Notable4", "AscendancyWarrior3Notable5", "AscendancyWarrior3Notable6_0", "AscendancyWarrior3Notable6_1", "AscendancyWarrior3Notable6_10", "AscendancyWarrior3Notable6_11", "AscendancyWarrior3Notable6_12_", "AscendancyWarrior3Notable6_2", "AscendancyWarrior3Notable6_3", "AscendancyWarrior3Notable6_4_", "AscendancyWarrior3Notable6_5", "AscendancyWarrior3Notable6_6", "AscendancyWarrior3Notable6_7", "AscendancyWarrior3Notable6_8", "AscendancyWarrior3Notable6_9", "AscendancyWarrior3Small1", "AscendancyWarrior3Small2", "AscendancyWarrior3Small3", "AscendancyWarrior3Small4", "AscendancyWarrior3Small5", "AscendancyWarrior3Start"], transform: "translate(15205.67, -5282.25)" },
	Tactician: { nodes: ["AscendancyMercenary1Notable1", "AscendancyMercenary1Notable10_", "AscendancyMercenary1Notable2", "AscendancyMercenary1Notable3", "AscendancyMercenary1Notable4_", "AscendancyMercenary1Notable5", "AscendancyMercenary1Notable6", "AscendancyMercenary1Notable7", "AscendancyMercenary1Notable8", "AscendancyMercenary1Notable9_", "AscendancyMercenary1Small1", "AscendancyMercenary1Small10", "AscendancyMercenary1Small2", "AscendancyMercenary1Small3", "AscendancyMercenary1Small4", "AscendancyMercenary1Small5_", "AscendancyMercenary1Small6", "AscendancyMercenary1Small7_", "AscendancyMercenary1Small8", "AscendancyMercenary1Small9", "AscendancyMercenary1Start"], transform: "translate(-3277.76, -15697.90)" },
	Witchhunter: { nodes: ["AscendancyMercenary2Notable1", "AscendancyMercenary2Notable2", "AscendancyMercenary2Notable3_", "AscendancyMercenary2Notable4", "AscendancyMercenary2Notable5", "AscendancyMercenary2Notable6", "AscendancyMercenary2Notable7", "AscendancyMercenary2Notable8", "AscendancyMercenary2Small1", "AscendancyMercenary2Small2", "AscendancyMercenary2Small3", "AscendancyMercenary2Small4", "AscendancyMercenary2Small5", "AscendancyMercenary2Small6", "AscendancyMercenary2Small7", "AscendancyMercenary2Small8_", "AscendancyMercenary2Start"], transform: "translate(-26.76, -16189.12)" },
	"Gemling Legionnaire": { nodes: ["AscendancyMercenary3Notable1_", "AscendancyMercenary3Notable2", "AscendancyMercenary3Notable2_1", "AscendancyMercenary3Notable2_2_", "AscendancyMercenary3Notable2_3_", "AscendancyMercenary3Notable3", "AscendancyMercenary3Notable4", "AscendancyMercenary3Notable5__", "AscendancyMercenary3Notable6", "AscendancyMercenary3Notable7", "AscendancyMercenary3Notable8", "AscendancyMercenary3Small1", "AscendancyMercenary3Small2", "AscendancyMercenary3Small3", "AscendancyMercenary3Small4", "AscendancyMercenary3Small5", "AscendancyMercenary3Small6", "AscendancyMercenary3Small7_", "AscendancyMercenary3Small8", "AscendancyMercenary3Start"], transform: "translate(3250.90, -15406.10)" },
	Oracle: { nodes: ["AscendancyDruid1Notable1", "AscendancyDruid1Notable2", "AscendancyDruid1Notable3", "AscendancyDruid1Notable4", "AscendancyDruid1Notable5", "AscendancyDruid1Notable6", "AscendancyDruid1Notable7", "AscendancyDruid1Notable8", "AscendancyDruid1Small1", "AscendancyDruid1Small2", "AscendancyDruid1Small3", "AscendancyDruid1Small4", "AscendancyDruid1Small5", "AscendancyDruid1Small6", "AscendancyDruid1Small7", "AscendancyDruid1Small8", "AscendancyDruid1Start"], transform: "translate(14279.29, 6881.12)" },
	Shaman: { nodes: ["AscendancyDruid2Notable1", "AscendancyDruid2Notable2", "AscendancyDruid2Notable3", "AscendancyDruid2Notable4", "AscendancyDruid2Notable5", "AscendancyDruid2Notable6", "AscendancyDruid2Notable7", "AscendancyDruid2Notable8", "AscendancyDruid2Small1", "AscendancyDruid2Small2", "AscendancyDruid2Small3", "AscendancyDruid2Small4_", "AscendancyDruid2Small5", "AscendancyDruid2Small6", "AscendancyDruid2Small7", "AscendancyDruid2Small8", "AscendancyDruid2Start"], transform: "translate(12279.24, 9183.00)" },
	Infernalist: { nodes: ["AscendancyWitch1Notable1", "AscendancyWitch1Notable10", "AscendancyWitch1Notable11_", "AscendancyWitch1Notable2", "AscendancyWitch1Notable3", "AscendancyWitch1Notable4", "AscendancyWitch1Notable5", "AscendancyWitch1Notable6", "AscendancyWitch1Notable7", "AscendancyWitch1Notable8", "AscendancyWitch1Notable9", "AscendancyWitch1Small1", "AscendancyWitch1Small10", "AscendancyWitch1Small11", "AscendancyWitch1Small2", "AscendancyWitch1Small3", "AscendancyWitch1Small4", "AscendancyWitch1Small5", "AscendancyWitch1Small6", "AscendancyWitch1Small7", "AscendancyWitch1Small8", "AscendancyWitch1Small9", "AscendancyWitch1Start__"], transform: "translate(9444.83, 13185.65)" },
	"Blood Mage": { nodes: ["AscendancyWitch2Notable1", "AscendancyWitch2Notable2_", "AscendancyWitch2Notable3", "AscendancyWitch2Notable4", "AscendancyWitch2Notable5", "AscendancyWitch2Notable6", "AscendancyWitch2Notable7", "AscendancyWitch2Notable8", "AscendancyWitch2Notable9", "AscendancyWitch2Small1", "AscendancyWitch2Small2", "AscendancyWitch2Small4_", "AscendancyWitch2Small5", "AscendancyWitch2Small6", "AscendancyWitch2Small7", "AscendancyWitch2Small8", "AscendancyWitch2Small9", "AscendancyWitch2Start"], transform: "translate(6319.56, 14714.00)" },
	Lich: { nodes: ["AscendancyWitch3Notable1", "AscendancyWitch3Notable2", "AscendancyWitch3Notable3", "AscendancyWitch3Notable4", "AscendancyWitch3Notable5", "AscendancyWitch3Notable6", "AscendancyWitch3Notable7", "AscendancyWitch3Notable8", "AscendancyWitch3Notable9", "AscendancyWitch3Small1", "AscendancyWitch3Small2", "AscendancyWitch3Small3", "AscendancyWitch3Small4", "AscendancyWitch3Small5", "AscendancyWitch3Small6_", "AscendancyWitch3Small7", "AscendancyWitch3Small8", "AscendancyWitch3Small9", "AscendancyWitch3Start_"], transform: "translate(3396.37, 15843.89)" },
	// Abyssal Lich replaces Lich at the same position — same nodes, start, and transform
	"Abyssal Lich": { nodes: ["AscendancyWitch3Notable1", "AscendancyWitch3Notable2", "AscendancyWitch3Notable3", "AscendancyWitch3Notable4", "AscendancyWitch3Notable5", "AscendancyWitch3Notable6", "AscendancyWitch3Notable7", "AscendancyWitch3Notable8", "AscendancyWitch3Notable9", "AscendancyWitch3Small1", "AscendancyWitch3Small2", "AscendancyWitch3Small3", "AscendancyWitch3Small4", "AscendancyWitch3Small5", "AscendancyWitch3Small6_", "AscendancyWitch3Small7", "AscendancyWitch3Small8", "AscendancyWitch3Small9", "AscendancyWitch3Start_"], transform: "translate(3396.37, 15843.89)" },
	Stormweaver: { nodes: ["AscendancySorceress1Notable1", "AscendancySorceress1Notable10", "AscendancySorceress1Notable2", "AscendancySorceress1Notable3", "AscendancySorceress1Notable4", "AscendancySorceress1Notable5", "AscendancySorceress1Notable6", "AscendancySorceress1Notable7", "AscendancySorceress1Notable8", "AscendancySorceress1Notable9", "AscendancySorceress1Small1", "AscendancySorceress1Small10", "AscendancySorceress1Small2", "AscendancySorceress1Small3", "AscendancySorceress1Small4", "AscendancySorceress1Small5", "AscendancySorceress1Small6", "AscendancySorceress1Small7", "AscendancySorceress1Small8", "AscendancySorceress1Small9", "AscendancySorceress1Start_"], transform: "translate(0.00, 16231.57)" },
	Chronomancer: { nodes: ["AscendancySorceress2Notable1_", "AscendancySorceress2Notable2", "AscendancySorceress2Notable3", "AscendancySorceress2Notable4", "AscendancySorceress2Notable5", "AscendancySorceress2Notable6", "AscendancySorceress2Notable7", "AscendancySorceress2Notable8", "AscendancySorceress2Small1", "AscendancySorceress2Small2", "AscendancySorceress2Small3", "AscendancySorceress2Small4", "AscendancySorceress2Small5", "AscendancySorceress2Small6", "AscendancySorceress2Small7", "AscendancySorceress2Small8", "AscendancySorceress2Start"], transform: "translate(-3230.12, 15709.65)" },
	"Disciple of Varashta": { nodes: ["AscendancySorceress3Notable1", "AscendancySorceress3Notable10_", "AscendancySorceress3Notable11", "AscendancySorceress3Notable12_", "AscendancySorceress3Notable13", "AscendancySorceress3Notable14", "AscendancySorceress3Notable15", "AscendancySorceress3Notable16", "AscendancySorceress3Notable17", "AscendancySorceress3Notable18", "AscendancySorceress3Notable2", "AscendancySorceress3Notable3", "AscendancySorceress3Notable5_", "AscendancySorceress3Notable6", "AscendancySorceress3Notable7", "AscendancySorceress3Notable8", "AscendancySorceress3Notable9", "AscendancySorceress3Small1", "AscendancySorceress3Small2", "AscendancySorceress3Small4", "AscendancySorceress3Small5", "AscendancySorceress3Small6_", "AscendancySorceress3Start"], transform: "translate(-6262.52, 14753.70)" },
	"Martial Artist": { nodes: ["AscendancyMonk1Notable1_", "AscendancyMonk1Notable2", "AscendancyMonk1Notable3", "AscendancyMonk1Notable4", "AscendancyMonk1Notable5", "AscendancyMonk1Notable6", "AscendancyMonk1Notable7", "AscendancyMonk1Notable8", "AscendancyMonk1Small1", "AscendancyMonk1Small2", "AscendancyMonk1Small3", "AscendancyMonk1Small4", "AscendancyMonk1Small5", "AscendancyMonk1Small6", "AscendancyMonk1Small7", "AscendancyMonk1Small8", "AscendancyMonk1Start"], transform: "translate(-12067.82, 10991.35)" },
	Invoker: { nodes: ["AscendancyMonk2Notable1_", "AscendancyMonk2Notable2_", "AscendancyMonk2Notable3", "AscendancyMonk2Notable4", "AscendancyMonk2Notable5", "AscendancyMonk2Notable6", "AscendancyMonk2Notable7_", "AscendancyMonk2Notable8", "AscendancyMonk2Notable9", "AscendancyMonk2Small1", "AscendancyMonk2Small10_", "AscendancyMonk2Small2", "AscendancyMonk2Small3", "AscendancyMonk2Small4", "AscendancyMonk2Small5", "AscendancyMonk2Small6", "AscendancyMonk2Small7", "AscendancyMonk2Small8", "AscendancyMonk2Small9", "AscendancyMonk2Start"], transform: "translate(-14149.30, 8115.00)" },
	"Acolyte of Chayula": { nodes: ["34567", "60251", "AscendancyMonk3Notable1", "AscendancyMonk3Notable2", "AscendancyMonk3Notable3_", "AscendancyMonk3Notable4", "AscendancyMonk3Notable5", "AscendancyMonk3Notable6", "AscendancyMonk3Notable6_2", "AscendancyMonk3Notable6_3", "AscendancyMonk3Notable6_Choice", "AscendancyMonk3Notable7", "AscendancyMonk3Notable8", "AscendancyMonk3Notable9", "AscendancyMonk3Small1", "AscendancyMonk3Small2", "AscendancyMonk3Small3", "AscendancyMonk3Small4_", "AscendancyMonk3Small5", "AscendancyMonk3Small6", "AscendancyMonk3Small7_", "AscendancyMonk3Small8", "AscendancyMonk3Small9", "AscendancyMonk3Start"], transform: "translate(-15340.33, 5000.92)" },
};

export const classAscendancies: Record<string, string[]> = {
	Ranger: ["Deadeye", "Pathfinder"],
	Huntress: ["Amazon", "Spirit Walker", "Ritualist"],
	Warrior: ["Titan", "Warbringer", "Smith of Kitava"],
	Mercenary: ["Tactician", "Witchhunter", "Gemling Legionnaire"],
	Druid: ["Oracle", "Shaman"],
	Witch: ["Infernalist", "Blood Mage", "Lich", "Abyssal Lich"],
	Sorceress: ["Stormweaver", "Chronomancer", "Disciple of Varashta"],
	Monk: ["Martial Artist", "Invoker", "Acolyte of Chayula"],
};

export const ascendancyNames: Record<string, string> = {
	Deadeye: "Deadeye",
	Pathfinder: "Pathfinder",
	Amazon: "Amazon",
	"Spirit Walker": "Spirit Walker",
	Ritualist: "Ritualist",
	Titan: "Titan",
	Warbringer: "Warbringer",
	"Smith of Kitava": "Smith of Kitava",
	Tactician: "Tactician",
	Witchhunter: "Witchhunter",
	"Gemling Legionnaire": "Gemling Legionnaire",
	Oracle: "Oracle",
	Shaman: "Shaman",
	Infernalist: "Infernalist",
	"Blood Mage": "Blood Mage",
	Lich: "Lich",
	"Abyssal Lich": "Abyssal Lich",
	Stormweaver: "Stormweaver",
	Chronomancer: "Chronomancer",
	"Disciple of Varashta": "Disciple of Varashta",
	"Martial Artist": "Martial Artist",
	Invoker: "Invoker",
	"Acolyte of Chayula": "Acolyte of Chayula",
};

export const ascendancyStartNodes: Record<string, string> = {
	Deadeye: "AscendancyRanger1Start",
	Pathfinder: "AscendancyRanger3Start",
	Amazon: "AscendancyHuntress1Start",
	"Spirit Walker": "AscendancyHuntress2Start",
	Ritualist: "AscendancyHuntress3Start",
	Titan: "AscendancyWarrior1Start",
	Warbringer: "AscendancyWarrior2Start",
	"Smith of Kitava": "AscendancyWarrior3Start",
	Tactician: "AscendancyMercenary1Start",
	Witchhunter: "AscendancyMercenary2Start",
	"Gemling Legionnaire": "AscendancyMercenary3Start",
	Oracle: "AscendancyDruid1Start",
	Shaman: "AscendancyDruid2Start",
	Infernalist: "AscendancyWitch1Start__",
	"Blood Mage": "AscendancyWitch2Start",
	Lich: "AscendancyWitch3Start_",
	"Abyssal Lich": "AscendancyWitch3Start_",
	Stormweaver: "AscendancySorceress1Start_",
	Chronomancer: "AscendancySorceress2Start",
	"Disciple of Varashta": "AscendancySorceress3Start",
	"Martial Artist": "AscendancyMonk1Start",
	Invoker: "AscendancyMonk2Start",
	"Acolyte of Chayula": "AscendancyMonk3Start",
};
